# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 53cd9ac63b64ab83b2906aae55884b9055207fef1f8b607ecb731032a95ba8b8493b66e69f4d51f681783e83c5362c3f1a7d00d4d7fdfc5b3e13981d976003c6

test:
  secret_key_base: df41ea5bc03b6a1bc13328ba7423ff95f21913f959d48c6e36b6e0ef04db9c6c3afbc52d1859cfce352e8aaff5ed8b65d7e6dfdbf4f1f8d74e12a72748d3a290

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
